---
- name: Converge
  hosts: all

  vars:
    dnscrypt_proxy_require_dnssec: true

    dnscrypt_proxy_blocked_names:
      - google.com
      - facebook.com

    dnscrypt_proxy_forwarding_rules:
      - name: lan
        resolver: 192.168.1.1

  roles:
    - dannixon.services.dnscrypt_proxy
