---
- name: Ensure package is installed
  become: true
  package:
    name: grafana
    state: present

- name: Ensure service is enabled and running
  service:
    name: grafana
    enabled: true
    state: started
  tags:
    - molecule-notest
