---
namespace: dannixon
name: services

version: 0.0.17

readme: readme.md

authors:
  - Dan Nixon <dan@dan-nixon.com>

description: Services deployment and configurations

license: MIT

repository: https://github.com/DanNixon/ansible-services
issues: https://github.com/DanNixon/ansible-services/issues
