---
- name: Ensure DMRGateway is installed
  become: true
  become_user: aur_builder
  ansible.legacy.aur:
    name: dmrgateway-git
    state: "{{ dmrgateway_package }}"

- name: Ensure systemd units are present
  become: true
  copy:
    src: dmrgateway.service
    dest: /usr/lib/systemd/system
    mode: "u=rw,g=r,o=r"

- name: Ensure config is present
  become: true
  template:
    src: dmrgateway.ini
    dest: /etc/
    mode: "u=r,g=r,o="
  notify:
    - Restart DMRGateway

- name: Ensure service is running
  become: true
  service:
    name: dmrgateway
    enabled: true
    state: started
  tags:
    - molecule-notest
