---
- name: Perform platform specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files: "install_{{ ansible_distribution }}.yml"
      skip: true

- name: Ensure Netdata is installed
  become: true
  package:
    name: netdata
    state: present

- name: Ensure the Netdata service is enabled and running
  become: true
  service:
    name: netdata
    state: started
    enabled: true
  tags:
    - molecule-notest
