---
- name: Remove existing IPv4 leases
  become: true
  ansible.builtin.file:
    path: /var/lib/kea/kea-leases4.csv
    state: absent
  notify:
    - Restart kea-dhcp4

- name: Remove existing IPv6 leases
  become: true
  ansible.builtin.file:
    path: /var/lib/kea/kea-leases6.csv
    state: absent
  notify:
    - Restart kea-dhcp6
