---
- name: "Ensure {{ service }} configuration is present"
  become: true
  ansible.builtin.template:
    src: kea.conf.j2
    dest: "/etc/kea/{{ service }}.conf"
    mode: "u=r,g=r,o=r"
    validate: "{{ service }} -t %s"
  when: enabled
  notify:
    - "Restart {{ service }}"

- name: "Ensure {{ service }} is configured"
  become: true
  ansible.builtin.service:
    name: "{{ service }}.service"
    enabled: "{{ enabled }}"
    state: "{{ 'started' if enabled else 'stopped' }}"
  tags:
    - molecule-notest
