---
- name: Ensure Git is installed
  become: true
  ansible.builtin.package:
    name: git
    state: present

- name: Ensure user exists
  become: true
  ansible.builtin.user:
    name: git-collage
    password: "!"
    shell: /usr/bin/nologin
    update_password: always
    state: present

- name: Ensure git-collage binary is present
  become: true
  ansible.builtin.get_url:
    url: https://github.com/DanNixon/git-collage/releases/download/v0.4.0/git-collage
    dest: /usr/bin/git-collage
    mode: "u=rx,g=rx,o=rx"

- name: Ensure systemd service is present
  become: true
  ansible.builtin.copy:
    src: git-collage.service
    dest: /usr/lib/systemd/system/
    mode: "u=rw,g=rw,o=r"

- name: Ensure systemd timer is present
  become: true
  ansible.builtin.template:
    src: git-collage.timer
    dest: /usr/lib/systemd/system/
    mode: "u=rw,g=rw,o=r"

- name: Ensure configuration is present
  become: true
  ansible.builtin.copy:
    content: "{{ git_collage_config }}"
    dest: /etc/git-collage.toml
    mode: "u=r,g=r,o=r"

- name: Ensure timer is enabled
  become: true
  ansible.builtin.service:
    name: git-collage.timer
    enabled: true
    state: started
  tags:
    - molecule-notest
