---
- name: Ensure dependencies are installed
  become: true
  package:
    name:
      - gcc
      - git
      - go
      - libolm
    state: present

- name: Obtain code
  become: true
  ansible.builtin.git:
    repo: "{{ go_neb_repo }}"
    version: "{{ go_neb_revision }}"
    dest: /var/go-neb
  notify: Build executable

- name: Ensure a service group exists
  become: true
  group:
    name: go-neb
    state: present

- name: Ensure a service user exists
  become: true
  user:
    name: go-neb
    group: go-neb
    password: "!"
    update_password: always
    state: present

- name: Ensure data directory exists
  become: true
  file:
    path: /var/lib/go-neb
    mode: "u=rwx,g=rx,o=rx"
    owner: go-neb
    group: go-neb
    state: directory

- name: Ensure configuration file is up to date
  become: true
  template:
    src: go-neb.yml
    dest: /etc/
    mode: "u=r,g=r,o="
    owner: go-neb
    group: go-neb
  notify: Restart Go-NEB

- name: Ensure systemd environment file is present
  become: true
  template:
    src: go-neb
    dest: /etc/conf.d/
    mode: "u=r,g=r,o=r"
  notify: Restart Go-NEB

- name: Ensure systemd unit is present
  become: true
  template:
    src: go-neb.service
    dest: /usr/lib/systemd/system/
    mode: "u=r,g=r,o=r"
  notify: Reload systemd daemon

- name: Flush handlers
  meta: flush_handlers

- name: Ensure service is enabled and running
  become: true
  service:
    name: go-neb.service
    enabled: true
    state: started
  tags:
    - molecule-notest
