---
- name: Ensure dnscrypt-proxy is installed
  become: true
  ansible.builtin.package:
    name: dnscrypt-proxy
    state: present

- name: Ensure dnscrypt-proxy configuration is present
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/dnscrypt-proxy/{{ item }}"
    mode: "u=rw,g=r,o=r"
  loop:
    - blocked-names.txt
    - forwarding-rules.txt
    - dnscrypt-proxy.toml
  notify:
    - Restart dnscrypt-proxy

- name: Ensure the dnscrypt-proxy service is enabled and running
  become: true
  ansible.builtin.service:
    name: dnscrypt-proxy
    state: started
    enabled: true
  tags:
    - molecule-notest

- name: Ensure system resolver is configured
  become: true
  ansible.builtin.copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: "u=rw,g=r,o=r"
    attributes: +i
  tags:
    - molecule-notest

- name: Ensure helper scripts are present
  become: true
  ansible.builtin.copy:
    src: dnscrypt-proxy-blocked-count
    dest: /usr/sbin/
    mode: "u=rx,g=rx,o=rx"
