---
- name: Converge
  hosts: all

  vars:
    traefik_static_config:
      entryPoints:
        web:
          address: ":80"
          http:
            redirections:
              entryPoint:
                to: websecure
                scheme: https
                permanent: true
        websecure:
          address: ":443"

    traefik_dynamic_configs:
      - name: test
        conf:
          tls:
            certificates:
              - certFile: cert.pem
                keyFile: key.pem
          http:
            routers:
              first:
                entryPoints:
                  - websecure
                tls: {}
                rule: "Host(`example.com`)"
                service: first

            services:
              first:
                loadBalancer:
                  servers:
                    - url: http://srv1.backend.example.com
                    - url: http://srv2.backend.example.com

  roles:
    - dannixon.traefik
