---
galaxy_info:
  author: dannixon
  description: Ensures SSH server has a sensible configuration
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux
    - name: Ubuntu

dependencies: []
