---
git_mirror_update_interval: weekly

git_mirror_config:
  - directory: /var/srv/git/mirrors
    repositories:
      - name: ansible-services
        url: https://github.com/DanNixon/ansible-services.git
