---
- name: Reload systemd daemon
  become: true
  systemd:
    daemon_reload: true
  when: molecule_yml is not defined

- name: Restart omada-controller
  become: true
  service:
    name: omada-controller
    state: restarted
  when: molecule_yml is not defined
