---
- name: Platform specific installation
  include_tasks: "{{ item }}"
  with_first_found:
    - files: "install_{{ ansible_distribution }}.yml"

- name: Ensure Borgmatic configuration is present
  become: true
  template:
    src: config.yaml
    dest: /etc/borgmatic/
    mode: "u=r,g=r,o="
    owner: "{{ borg_borgmatic_user }}"

# TODO: automation
