---
- name: Platform specific installation
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files: "install_{{ ansible_distribution }}.yml"

- name: Ensure Borgmatic configuration is present
  become: true
  ansible.builtin.template:
    src: config.yaml
    dest: /etc/borgmatic/
    mode: "u=r,g=r,o="
    owner: "{{ borg_borgmatic_user }}"

- name: Ensure systemd units are present
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/usr/lib/systemd/system/"
    mode: "u=r,g=r,o=r"
  loop:
    - borgmatic.service
    - borgmatic.timer
  notify: Reload systemd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure scheduled backups are configured
  become: true
  ansible.builtin.systemd:
    name: borgmatic.timer
    enabled: "{{ borg_borgmatic_enable_scheduled_backups }}"
    state: "{{ 'started' if borg_borgmatic_enable_scheduled_backups else 'stopped' }}"
  tags:
    - molecule-notest
