---
- name: Ensure MPD is installed
  become: true
  ansible.builtin.package:
    name: mpd
    state: present

- name: Ensure MPD configuration directory exists
  ansible.builtin.file:
    path: "{{ mpd_config_dir[mpd_service_scope] }}"
    state: directory
    mode: "u=rwx,g=,o="
  when: mpd_service_scope == "user"

- name: Ensure MPD configuration is present
  ansible.builtin.template:
    src: mpd.conf.j2
    dest: "{{ mpd_config_dir[mpd_service_scope] }}/mpd.conf"
    mode: "u=r,g=,o="
  notify:
    - Restart MPD

- name: Ensure MPD service is started
  ansible.builtin.systemd:
    name: mpd
    scope: "{{ mpd_service_scope }}"
    enabled: true
    state: started
  tags:
    - molecule-notest
