---
- name: Ensure package is installed
  become: true
  package:
    name: prometheus
    state: present

- name: Ensure configuration is present
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "u=r,g=r,o=r"
  loop:
    - src: prometheus.yml
      dest: /etc/prometheus
    - src: prometheus
      dest: /etc/conf.d
  notify:
    - Restart Prometheus

- name: Ensure service is enabled and running
  become: true
  service:
    name: prometheus
    enabled: true
    state: started
  tags:
    - molecule-notest
