---
- name: Ensure package is installed
  become: true
  ansible.builtin.package:
    name: traefik
    state: present

- name: Ensure Traefik configuration is present
  become: true
  ansible.builtin.template:
    src: traefik.yml
    dest: /etc/traefik
    mode: "u=r,g=r,o=r"
  notify:
    - Restart Traefik

- name: Ensure Traefik dynamic configuration directory is present
  become: true
  ansible.builtin.file:
    path: /etc/traefik/dynamic
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Ensure Traefik dynamic configurations are present
  become: true
  ansible.builtin.template:
    src: traefik_dynamic.yml
    dest: "/etc/traefik/dynamic/{{ item.name }}.yml"
    mode: "u=r,g=r,o=r"
  loop: "{{ traefik_dynamic_configs }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure service is enabled and running
  ansible.builtin.service:
    name: traefik
    enabled: true
    state: started
  tags:
    - molecule-notest
