---
- name: Ensure dependencies are installed
  become: true
  package:
    name:
      - git
      - go
    state: present

- name: Obtain code
  become: true
  ansible.builtin.git:
    repo: "{{ octopusenergy_influxdb_repo }}"
    version: "{{ octopusenergy_influxdb_revision }}"
    dest: /var/octopusenergy-influxdb
  notify: Build executable

- name: Ensure a service group exists
  become: true
  group:
    name: octopusenergy-influxdb
    state: present

- name: Ensure a service user exists
  become: true
  user:
    name: octopusenergy-influxdb
    group: octopusenergy-influxdb
    password: "!"
    update_password: always
    state: present

- name: Ensure configuration file is up to date
  become: true
  template:
    src: octopusenergy-influxdb.yml
    dest: /etc/
    mode: "u=r,g=r,o="
    owner: octopusenergy-influxdb
    group: octopusenergy-influxdb

- name: Ensure systemd units are present
  become: true
  template:
    src: "{{ item }}"
    dest: /usr/lib/systemd/system/
    mode: "u=r,g=r,o=r"
  loop:
    - octopusenergy-influxdb.service
    - octopusenergy-influxdb.timer
  notify: Reload systemd daemon

- name: Flush handlers
  meta: flush_handlers

- name: Enable timer
  become: true
  systemd:
    name: octopusenergy-influxdb.timer
    enabled: true
  tags:
    - molecule-notest
