---
- name: Converge
  hosts: all

  vars:
    prometheus_args: "--storage.tsdb.retention.size=100GB"

    prometheus_config:
      global:
        scrape_interval: 15s

    prometheus_rule_groups:
      - name: example
        rules:
          - record: job:http_inprogress_requests:sum
            expr: sum by (job) (http_inprogress_requests)

  roles:
    - dannixon.prometheus
