---
- name: Ensure Syncthing APT key is added
  become: true
  ansible.builtin.apt_key:
    url: https://syncthing.net/release-key.txt
    state: present

- name: Ensure Syncthing APT repository is added
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present

- name: Update APT repos
  become: true
  ansible.builtin.apt:
    update_cache: true
