---
galaxy_info:
  author: dannixon
  description: Installs and configures backups with Borg and Borgmatic
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: ArchLinux
    - name: Ubuntu

dependencies: []
