---
- name: Ensure Bind is installed
  become: true
  ansible.builtin.package:
    name: bind
    state: present

- name: Configure rndc
  include_tasks: rndc_confgen.yml
  when: bind_rndc_generate_key

- name: Ensure configuration is present
  become: true
  ansible.builtin.template:
    src: named.conf.j2
    dest: /etc/named.conf
    mode: "u=r,g=r,o=r"
    validate: named-checkconf %s
  notify: Restart Bind

- name: Configure zones
  include_tasks: zones.yml
  when: bind_update_zones

- name: Ensure service is enabled and running
  become: true
  ansible.builtin.service:
    name: named.service
    enabled: true
    state: started
  tags:
    - molecule-notest
