---
- name: Ensure zone file is present and up to date
  become: true
  template:
    src: zone.j2
    dest: "/var/named/{{ zone.filename }}"
    owner: named
    group: named
    mode: "u=r,g=r,o=r"
    validate: "named-checkzone -dD {{ zone.origin }} %s"
  notify:
    - Restart Bind
  register: zone_file

- name: Ensure zone journal is discarded
  become: true
  file:
    dest: "/var/named/{{ zone.filename }}.jnl"
    state: absent
  when: zone_file.changed
