---
- name: Converge
  hosts: all

  vars:
    kea_dhcp4_enable: true
    kea_dhcp4_config:
      loggers:
        - name: kea-dhcp4
          severity: DEBUG
          output_options:
            - output: stdout
              pattern: "[%-5p %c] %m\n"

    kea_dhcp6_enable: true
    kea_dhcp6_config:
      loggers:
        - name: kea-dhcp6
          severity: DEBUG
          output_options:
            - output: stdout
              pattern: "[%-5p %c] %m\n"

    kea_dhcp_ddns_enable: true
    kea_dhcp_ddns_config:
      loggers:
        - name: kea-dhcp-ddns
          severity: DEBUG
          output_options:
            - output: stdout
              pattern: "[%-5p %c] %m\n"

  roles:
    - kea
