---
- name: Perform platform specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files: "install_{{ ansible_distribution }}.yml"
      skip: true

- name: Ensure SSH password authentication is disabled
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    line: PasswordAuthentication no
    state: present
  notify:
    - Restart sshd

- name: Ensure sshd is enabled and running
  become: true
  service:
    name: sshd
    state: started
    enabled: true
  tags:
    - molecule-notest
