---
name: "dannixon.services.influxdb"

on:
  push:
    paths:
      - 'roles/influxdb/**'
      - '.github/workflows/influxdb.yml'
  pull_request:
    paths:
      - 'roles/influxdb/**'
      - '.github/workflows/influxdb.yml'

jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - uses: dannixon/ansible-testing/actions/test_role@v1
        with:
          role: influxdb
